<a href="https://colab.research.google.com/github/jazmichewcam/EDP1/blob/main/metodo%20-jacobi%20-jaz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`METODO DE JACOBI`**

---

Implementación del método iterativo de Jacobi para resolver sistemas lineales Ax = b.
El código incluye:
- Construcción de la tabla de iteraciones.
- Cálculo del error en norma infinito.
- Control de convergencia con tolerancia y número máximo de iteraciones.


    Método iterativo de Jacobi para resolver el sistema lineal Ax = b.

    Parámetros
    ----------
    A : matriz (lista o np.array)
        Matriz de coeficientes del sistema.
    b : vector (lista o np.array)
        Vector de términos independientes.
    x0 : vector (lista o np.array)
        Aproximación inicial de la solución.
    TOL : float
        Tolerancia para el criterio de convergencia.
    N : int
        Número máximo de iteraciones.
    nombres : lista de str
        Nombres de las variables (opcional).

    Retorna
    -------
    x_final : np.array
        Aproximación de la solución al sistema.
    tabla : pd.DataFrame
        Tabla con el historial de las iteraciones.
    exito : bool
        True si el método converge, False en caso contrario.

In [10]:
import numpy as np
import pandas as pd
from IPython.display import display

# Configuración de Pandas para mostrar más decimales y ajustar ancho
pd.set_option("display.precision", 8)
pd.set_option("display.width", 140)


# ==========================================================
#               FUNCIÓN DEL MÉTODO DE JACOBI
# ==========================================================
def jacobi(A, b, x0, TOL, N, nombres):

    # Convertimos a arreglos de tipo float
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1)
    x_old = np.array(x0, dtype=float).reshape(-1)
    n = A.shape[0]

    # Si no se pasan nombres, se generan automáticamente (x1, x2, ...)
    if nombres is None:
        nombres = [f"x{i+1}" for i in range(n)]

    historial = []   # Guardar cada iteración
    exito = False    # Bandera de convergencia

    # ==========================================================
    # Iteración 0 (condición inicial)
    # ==========================================================
    fila0 = {"iter": 0}
    for name, val in zip(nombres, x_old):
        fila0[name] = val
    historial.append(fila0)

    # Inicializamos el contador de iteraciones
    k = 1

    # ==========================================================
    # Bucle de iteraciones
    # ==========================================================
    while k <= N:
        x_new = np.zeros_like(x_old)

        # ------------------------------------------------------
        # Paso 3: Cálculo de nuevas aproximaciones
        # Fórmula: x_i^(k+1) = (b_i - Σ a_ij * x_j^(k)) / a_ii
        # ------------------------------------------------------
        for i in range(n):
            aii = A[i, i]
            suma = sum(A[i, j] * x_old[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - suma) / aii

        # ------------------------------------------------------
        # Paso 4: Cálculo del error con norma infinito
        # ------------------------------------------------------
        err_inf = np.linalg.norm(x_new - x_old, ord=np.inf)

        # Guardamos resultados de esta iteración en historial
        fila = {"iter": k}
        for name, val in zip(nombres, x_new):
            fila[name] = val
        fila["err_inf"] = err_inf
        historial.append(fila)

        # ------------------------------------------------------
        # Verificación de convergencia
        # ------------------------------------------------------
        if err_inf < TOL:
            exito = True
            x_final = x_new.copy()
            break

        # ------------------------------------------------------
        # Paso 5: Preparamos siguiente iteración
        # ------------------------------------------------------
        k += 1
        x_old = x_new

    # Si no converge en N iteraciones, devolvemos última aproximación
    if not exito:
        x_final = x_old

    # Construcción de la tabla de resultados
    cols = ["iter"] + nombres
    tabla = pd.DataFrame(historial)[cols + (["err_inf"] if "err_inf" in historial[-1] else [])]

    return x_final, tabla, exito


# ==========================================================
#                 DEFINICIÓN DEL SISTEMA Ax=b
# ==========================================================
A = [[4, -1, -1, 0],
     [1, -4, 0, 1],
     [1, 0, -4, 1],
     [0, 1, 1, -4]]

# Nota: Si en la diagonal hay ceros, es necesario intercambiar renglones,
# ya que el método Jacobi no puede dividir entre cero.
b = [0, -2/3, -8/9, -14/9]


# ==========================================================
#                 PARÁMETROS DEL PROBLEMA
# ==========================================================
x0  = [0, 0, 0, 0]   # Vector inicial
TOL = 1e-10          # Tolerancia
N   = 100            # Número máximo de iteraciones


# ==========================================================
#                EJECUCIÓN DEL MÉTODO
# ==========================================================
x_aprox, tabla, exito = jacobi(A, b, x0, TOL, N, nombres=["A", "B", "C", "D"])

# Mostrar la tabla de iteraciones
display(tabla.style.hide(axis="index"))

# Imprimir la solución aproximada
print("Solución aproximada X=(A, B, C, D):", x_aprox)

Solución aproximada X=(A, B, C, D): [0.19444444 0.36111111 0.41666667 0.58333333]